[personal]
first_name = "Sam"
last_name = "Wlody"
profile_image = "portrait.png"
language = "en"
include_icons = true

[personal.info]
address = "Brooklyn, NY"
telephone = "+1 (914) 960-8475"

[personal.info.email]
link = "mailto:sam@swlody.dev"
label = "sam@swlody.dev"

[personal.info.linkedin]
link = "https://linkedin.com/in/sam-wlody"
label = "sam-wlody"

[personal.info.github]
link = "https://github.com/swlody"
label = "swlody"

[personal.info.homepage]
link = "https://swlody.dev"
label = "swlody.dev"

[personal.icon]
address = "house"
telephone = "phone"
email = "envelope"
linkedin = "linkedin"
github = "github"
homepage = "globe"

[section.icon]
education = "graduation-cap"
experience = "briefcase"
languages = "language"
projects = "wrench"
sabbatical = "code"
personal = "brain"
profile = "id-card"
references = "users"
skills = "cogs"

# To change fill_color to white, replace value with "#ffffff"
[layout]
fill_color = "#ffffff"
paper_size = "us-letter"
accent_color = "#d4d2cc"
# deafult value is 71%
left_pane_width = "69%"

[layout.text]
font = "HK Grotesk"
size = "9pt"
cover_letter_size = "11pt"

[layout.text.color]
light = "#ededef"
medium = "#78787e"
dark = "#3c3c42"

[language.en]
subtitle = "Software Engineer"

[import]
path = "lib.typ"
fontawesome = "@preview/fontawesome:0.5.0"
